Assignment/3/Solution/code/book_keep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls'))
]

Assignment/3/Solution/code/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path("", views.index, name='index'),
    path("books", views.BookListView.as_view(), name='book_list'),
    path("members", views.MemberListView.as_view(), name='member_list'),
    path("bookings", views.BookingListView.as_view(), name='booking_list'),
    path("bookings/add", views.CreateBookingView.as_view(), name='create_booking'),

]

Assignment/3/Solution/code/main/models.py
from django.db import models
from datetime import datetime
from django import forms


# Create your models here.
class Book(models.Model):

    title = models.CharField(max_length=50, blank=False)
    author = models.CharField(max_length=50, blank=False)
    publish_year = models.DecimalField(max_digits=4, decimal_places=0)
    edition = models.IntegerField(default=1)
    
    def __str__(self) -> str:
        return f'{self.title}, by: {self.author} - {self.publish_year}, ed: {self.edition}'

class Member(models.Model):

    name = models.CharField(max_length=30, blank=False)
    address = models.CharField(max_length=100)
    phone_number = models.DecimalField(max_digits=11, decimal_places=0)
    
    def __str__(self) -> str:
        return self.name

class Booking(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    expiration_date = models.DateField()
    
    def save(self, *args, **kwargs):
        old_booking = Booking.objects.filter(book=self.book, member=self.member)
        if not old_booking.exists():
            super().save(*args, **kwargs)

    def clean(self):
        if self.expiration_date < datetime.now().date():
            raise forms.ValidationError("The expiration date is already gone!")
        if  Booking.objects.filter(member=self.member).exists():
            latest_booking = Booking.objects.filter(member=self.member).latest('expiration_date')
            if datetime.now().date() < latest_booking.expiration_date:
                if latest_booking.book != self.book:
                    raise forms.ValidationError("An active booking already exists!")
                elif latest_booking.expiration_date < self.expiration_date:
                    Booking.objects.filter(pk=latest_booking.pk).update(expiration_date=self.expiration_date)
                else:
                    raise forms.ValidationError("An active booking has longer expiration date!")

Assignment/3/Solution/code/main/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.http import HttpResponse
from . import models


# Create your views here.

def index(request):
    return HttpResponse("Hello. You're at the project index.")

class MemberListView(ListView):
    model = models.Member
    template_name = 'main/member_list.html'

class BookListView(ListView):
    model = models.Book
    template_name = 'main/book_list.html'

class BookingListView(ListView):
    model = models.Booking
    template_name = 'main/booking_list.html'
    def get_queryset(self):
        return models.Booking.objects.order_by('-expiration_date')

class CreateBookingView(CreateView):
    model = models.Booking
    fields = ('member', 'book', 'expiration_date')

    template_name = 'main/create_booking.html'
    success_url = reverse_lazy('main:booking_list')
    

Assignment/3/Solution/code/main/templates/main/book_list.html
<h2>
    Available Books
</h2>

<ul>
    {% for book in object_list %}
    <li>{{ book }}</li>
    {% endfor %}
</ul>

Assignment/3/Solution/code/main/templates/main/booking_list.html
<h2>
    Bookings
</h2>
<table>
    <tr>
        <th>Member</th>
        <th>Book</th>
        <th>Exipration Date</th>
    </tr>
    {% for booking in object_list %}
    <tr>
    <td>{{booking.member}}</td> <td>{{ booking.book }}</td> <td>{{booking.expiration_date}}</td>
    </tr>
{% endfor %}
</table>
<a href="{% url 'main:create_booking' %}"> add </a>

Assignment/3/Solution/code/main/templates/main/create_booking.html
<h1>New Booking</h1>
    <form method="POST">

        {% csrf_token %}
        {{form.as_p}}

        <button type="submit">Save</button>
    </form>

Assignment/3/Solution/code/main/templates/main/member_list.html
<h2>
    Members
</h2>

<ul>
    {% for member in object_list %}
    <li>{{ member }}</li>
    {% endfor %}
</ul>